# [START django_app]
runtime: python39
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

# Warmup requests enabled, App Engine issues GET requests to /_ah/warmup.
# You can implement handlers for this request to perform application-specific tasks
inbound_services:
  - warmup

automatic_scaling:
  min_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

- url: /_ah/warmup  # just serve simple, quick
  static_files: static/admin/img/search.svg
  upload: static/admin/img/search.svg

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]
