"""
Django settings for LandApp project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os

import requests

# NEED OVERRIDE
# This value is used in URL path, Swagger, GCS blob save dir etc.
API_VERSION = 'v1'

# BUSINESS related setting
# Verification Code setting
EMAIL_CODE_DIGIT = 4
EMAIL_CODE_LIFETIME_MIN = 5
# Room Bump setting
BUMP_CYCLE_SEC = 24 * 60 * 60  # 끌올 주기 (24h)
# Image thumbnail setting
THUMBNAIL_DIMENSION = (128, 128)  # 128x128
THUMBNAIL_URL_SUFFIX = '=thumbnail'  # https://<PUBLIC_URL_TO_IMAGE>=thumbnail

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Update the secret key to a value of your own before deploying the app.
SECRET_KEY = 'l4b#tsk77hyv#xi$+mir516p*tys)(_36ya5)4#h0$0gqivdw6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: App Engine's security features ensure that it is safe to
# have ALLOWED_HOSTS = ['*'] when the app is deployed. If you deploy a Django
# app not on App Engine, make sure to set an appropriate host here.
# See https://docs.djangoproject.com/en/2.1/ref/settings/
ALLOWED_HOSTS = ['*']

EC2_PRIVATE_IP = None
try:
    EC2_PRIVATE_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout=0.01).text
except requests.exceptions.RequestException:
    pass
if EC2_PRIVATE_IP:
    ALLOWED_HOSTS.append(EC2_PRIVATE_IP)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'django_extensions',
    'hitcount',
    'landapp',  # for custom command install
    'storages',
    'sorl.thumbnail',
    'api.models.user',
    'api.models.room',
    'api.models.room_image',
    'api.models.feedback',
    'api.models.image_test',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'landapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'landapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# django-storage for AWS S3 config
DEFAULT_FILE_STORAGE = 'infra.s3_storage.S3DefaultFileStorage'
AWS_ACCESS_KEY_ID = 'AKIAUMHSG7JBWFZBLQXP'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'landapp-test-s3'
AWS_STORAGE_IMAGE_LOCATION = 'image'
AWS_STORAGE_FILE_LOCATION = 'file'
AWS_STORAGE_MEDIA_LOCATION = 'media'
# Allow Signature V4 support
# https://github.com/jschneier/django-storages/issues/687
AWS_S3_SIGNATURE_VERSION = 's3v4'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# DRF configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '10/second'
    }
}

# Authentication
AUTH_USER_MODEL = 'user.User'

# JWT settings
JWT_AUTH = {
    # TODO: temporary measurement. need to change after proper auth system
    'JWT_VERIFY_EXPIRATION': False,
}

# Email setting
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'jin@landcorp.io'
EMAIL_HOST_PASSWORD = 'jpyqgmmmhyfpvxvr'
DEFAULT_FROM_EMAIL = 'support@landcorp.io'
EMAIL_PORT = 587

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = 'static'
STATIC_URL = '/static/'
