# Generated by Django 3.1.4 on 2021-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=255),
            preserve_default=False,
        ),
    ]
