# Generated by Django 3.1.4 on 2020-12-30 12:02

import api.base.code.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(default=api.base.code.models.generate_code, editable=False, max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email_to_verify', models.EmailField(max_length=255)),
                ('expires_at', models.DateTimeField(default=api.base.code.models.get_expires_at)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
