# Generated by Django 3.1.4 on 2021-01-14 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bumped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
