# Generated by Django 3.1.4 on 2021-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
