# Generated by Django 3.1.4 on 2021-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_image', '0002_auto_20210108_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='thumb_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
