# Generated by Django 3.1.4 on 2021-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_image', '0003_roomimage_thumb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='thumb_url',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='url',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='s3_filename',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
