# Generated by Django 3.1.4 on 2021-01-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_image', '0004_auto_20210108_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='s3_filename',
            new_name='filename',
        ),
    ]
